In [1]:
# Imports / global contants

# csv Dateien sind im Verzeichnis ../data zu finden

import pandas as pd
import glob
import os
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from matplotlib import figure
import math
import numpy as np
import seaborn as sns
from scipy.misc import electrocardiogram
from scipy.signal import find_peaks
import gc
import pylab

import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

from pandas.plotting import parallel_coordinates

%matplotlib inline

timeFormat = "%Y-%m-%dT%H:%M:%S.%fZ"

export = "../export/"
export_img = "../export/img/"
export_interactions = "../export/interaction/"

path = "../data/"

gtv_colormap = {1: 'rgb(54, 161, 185)', 2: 'rgb(0, 44, 61)', 3: 'rgb(233, 71, 74)'}
plot_bgcolor = 'rgba(239, 240, 231,.7)'

In [12]:
df_cleaned = pd.read_csv(rf'{export}cleanedStudy_interactionOnly.csv', sep=";")

In [42]:
# Beispiel-Daten erzeugen
np.random.seed(0)
zeiten = pd.date_range(start="2024-01-01", periods=200, freq="T")
werte = np.concatenate([
    np.zeros(60),              # 60 Nullwerte (vorzeitiger Start)
    np.random.rand(10),        # zufällige "Störung"
    np.zeros(45),              # noch eine Nullsequenz (zu kurz)
    np.random.normal(5, 1, 85) # echte Messung
])

df = pd.DataFrame({"zeit": zeiten, "wert": werte})
df["zeit"] = pd.to_datetime(df["zeit"])
df.set_index("zeit", inplace=True)

# Schwellenwert für "Null" (z.B. ≤ 0.1)
is_zero_like = df["wert"] <= 0.1

display(is_zero_like)

display(is_zero_like.loc[lambda x: x == True])

# Glättung: kurze Unterbrechungen ignorieren
smoothed = is_zero_like.rolling(window=5, center=True, min_periods=1).mean() > 0.5

# Gruppieren: gleiche True/False Blöcke finden
group_id = (smoothed != smoothed.shift()).cumsum()

display(group_id)

groups = df.groupby(group_id)

# Längere Nullblöcke identifizieren
to_remove = []
removed_durations = []

for _, group in groups:
    if (smoothed.loc[group.index[0]]):  # Nur Null-ähnliche Gruppen
        if len(group) > 50:
            to_remove.append(group.index)
            duration = group.index[-1] - group.index[0]
            removed_durations.append(duration)

# Indexes zusammenfassen und entfernen
remove_idx = pd.Index(np.concatenate(to_remove)) if to_remove else pd.Index([])
df_cleaned = df.drop(index=remove_idx)

# Ursprüngliche vs. korrigierte Dauer
original_duration = df.index[-1] - df.index[0]
corrected_duration = original_duration - sum(removed_durations, pd.Timedelta(0))

print("Ursprüngliche Dauer:", original_duration)
print("Dauer der entfernten Nullphasen:", sum(removed_durations, pd.Timedelta(0)))
print("Korrigierte Dauer:", corrected_duration)

zeit
2024-01-01 00:00:00     True
2024-01-01 00:01:00     True
2024-01-01 00:02:00     True
2024-01-01 00:03:00     True
2024-01-01 00:04:00     True
                       ...
2024-01-01 03:15:00    False
2024-01-01 03:16:00    False
2024-01-01 03:17:00    False
2024-01-01 03:18:00    False
2024-01-01 03:19:00    False
Name: wert, Length: 200, dtype: bool

zeit
2024-01-01 00:00:00    True
2024-01-01 00:01:00    True
2024-01-01 00:02:00    True
2024-01-01 00:03:00    True
2024-01-01 00:04:00    True
                       ...
2024-01-01 01:50:00    True
2024-01-01 01:51:00    True
2024-01-01 01:52:00    True
2024-01-01 01:53:00    True
2024-01-01 01:54:00    True
Name: wert, Length: 105, dtype: bool

zeit
2024-01-01 00:00:00    1
2024-01-01 00:01:00    1
2024-01-01 00:02:00    1
2024-01-01 00:03:00    1
2024-01-01 00:04:00    1
                      ..
2024-01-01 03:15:00    4
2024-01-01 03:16:00    4
2024-01-01 03:17:00    4
2024-01-01 03:18:00    4
2024-01-01 03:19:00    4
Name: wert, Length: 200, dtype: int32

Ursprüngliche Dauer: 0 days 03:19:00
Dauer der entfernten Nullphasen: 0 days 00:59:00
Korrigierte Dauer: 0 days 02:20:00

In [56]:
df_cleaned = pd.read_csv(rf'{export}cleanedStudy_interactionOnly.csv', sep=";")

proband = 18
block = 2
task = 4
trial = 3

display(df_cleaned)

exp_data = df_cleaned[(df_cleaned["Proband"] == proband) & (df_cleaned["Task"] == task) & (df_cleaned["Block"] == block) & (df_cleaned["Trial"] == trial)].reset_index(drop=True)

display(exp_data)

df_cleaned["DateTime"] = pd.to_datetime(df_cleaned["DateTime"])
df_cleaned.set_index("DateTime", inplace=True)

nan_values = df_cleaned["posX"] == (" -")

display(nan_values)

display(nan_values.loc[lambda x: x == True])

group_id = (nan_values != nan_values.shift()).cumsum()
groups = df_cleaned.groupby(group_id)

display(group_id)

to_remove = []
removed_frames = 0

for _, group in groups:
    val = nan_values.loc[group.index[0]]
    if isinstance(val, pd.Series):   
        val = val.iloc[0]  # Sicherstellen, dass es ein einzelner Wert ist
    if val:  # Nur Null-ähnliche Gruppen        
        to_remove.append(group.index)
        removed_frames += len(group)

display(to_remove)

remove_idx =  pd.Index(np.concatenate(to_remove)) if to_remove else pd.Index([])
df_cleaned2 = df_cleaned.drop(index=remove_idx)

print("Anzahl der entfernten Nullwerte:", removed_frames)

exp_data = df_cleaned2[(df_cleaned2["Proband"] == proband) & (df_cleaned2["Task"] == task) & (df_cleaned2["Block"] == block) & (df_cleaned2["Trial"] == trial)].reset_index(drop=True)

display(exp_data)

,Unnamed: 0,SampleIdx_global,SampleIdx_Proband,DateTime,State,mappingMethod,Task,TargetLayers,NumLayers,Trial,...,posZ,TimeStamp,iteractionType,currentLayer,Proband,shifted,Result,Block,Target,Target_Relative
0,0,135,135,2021-05-10T12:13:56.584Z,VIEW,direct,1,"['4', '5', '3', '1', '2']",6,0,...,NaN,NaN,NaN,NaN,1,1.0,START,1,4,0.666667
1,1,136,136,2021-05-10T12:13:56.602Z,INTERACTION,direct,1,"['4', '5', '3', '1', '2']",6,0,...,-,-,-,2,1,1.0,COMPLETED,1,4,0.666667
2,2,137,137,2021-05-10T12:13:56.633Z,INTERACTION,direct,1,"['4', '5', '3', '1', '2']",6,0,...,-,-,-,2,1,1.0,COMPLETED,1,4,0.666667
3,3,138,138,2021-05-10T12:13:56.676Z,INTERACTION,direct,1,"['4', '5', '3', '1', '2']",6,0,...,-,-,-,-,1,1.0,COMPLETED,1,4,0.666667
4,4,139,139,2021-05-10T12:13:56.697Z,INTERACTION,direct,1,"['4', '5', '3', '1', '2']",6,0,...,-,-,-,-,1,1.0,COMPLETED,1,4,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1535230,1535230,2360983,90204,2021-06-30T12:37:15.245Z,INTERACTION,widening,18,"['4', '5', '2', '3', '1']",6,4,...,-0.9999999,637606606352421800,1,6,24,54.0,FAILED,3,1,0.166667
1535231,1535231,2360984,90205,2021-06-30T12:37:15.291Z,INTERACTION,widening,18,"['4', '5', '2', '3', '1']",6,4,...,-0.9999999,637606606352861800,1,6,24,54.0,FAILED,3,1,0.166667
1535232,1535232,2360985,90206,2021-06-30T12:37:15.323Z,INTERACTION,widening,18,"['4', '5', '2', '3', '1']",6,4,...,-0.9999999,637606606353161900,1,6,24,54.0,FAILED,3,1,0.166667
1535233,1535233,2360986,90207,2021-06-30T12:37:15.361Z,INTERACTION,widening,18,"['4', '5', '2', '3', '1']",6,4,...,-0.9999999,637606606353551700,1,6,24,54.0,FAILED,3,1,0.166667
1535234,1535234,2360987,90208,2021-06-30T12:37:15.381Z,SUBTASK_STATE,widening,18,"['4', '5', '2', '3', '1']",6,4,...,NaN,NaN,NaN,NaN,24,54.0,FAILED,3,1,0.166667

,Unnamed: 0,SampleIdx_global,SampleIdx_Proband,DateTime,State,mappingMethod,Task,TargetLayers,NumLayers,Trial,...,posZ,TimeStamp,iteractionType,currentLayer,Proband,shifted,Result,Block,Target,Target_Relative
0,1189494,1855631,28737,2021-06-21T16:48:09.752Z,SUBTASK_STATE,widening,4,"['17', '5', '1', '9', '14']",18,3,...,NaN,NaN,NaN,NaN,18,22.0,START,2,9,0.5
1,1189495,1855632,28738,2021-06-21T16:48:09.784Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.769736648,637598980897781800,1,13,18,22.0,COMPLETED,2,9,0.5
2,1189496,1855633,28739,2021-06-21T16:48:09.825Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.8210525,637598980898231700,1,15,18,22.0,COMPLETED,2,9,0.5
3,1189497,1855634,28740,2021-06-21T16:48:09.868Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.8210525,637598980898619400,1,16,18,22.0,COMPLETED,2,9,0.5
4,1189498,1855635,28741,2021-06-21T16:48:09.900Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.8565788,637598980898949400,1,16,18,22.0,COMPLETED,2,9,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9554,1199048,1865185,38291,2021-06-21T16:54:14.981Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.335526258,637598984549783700,1,9,18,22.0,COMPLETED,2,9,0.5
9555,1199049,1865186,38292,2021-06-21T16:54:15.023Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.339473575,637598984550213600,1,9,18,22.0,COMPLETED,2,9,0.5
9556,1199050,1865187,38293,2021-06-21T16:54:15.063Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.339473575,637598984550603800,1,9,18,22.0,COMPLETED,2,9,0.5
9557,1199051,1865188,38294,2021-06-21T16:54:15.092Z,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,...,-0.339473575,637598984550873600,1,9,18,22.0,COMPLETED,2,9,0.5
9558,1199052,1865189,38295,2021-06-21T16:54:15.105Z,SUBTASK_STATE,widening,4,"['17', '5', '1', '9', '14']",18,3,...,NaN,NaN,NaN,NaN,18,22.0,COMPLETED,2,9,0.5

DateTime
2021-05-10 12:13:56.584000+00:00    False
2021-05-10 12:13:56.602000+00:00     True
2021-05-10 12:13:56.633000+00:00     True
2021-05-10 12:13:56.676000+00:00     True
2021-05-10 12:13:56.697000+00:00     True
                                    ...
2021-06-30 12:37:15.245000+00:00    False
2021-06-30 12:37:15.291000+00:00    False
2021-06-30 12:37:15.323000+00:00    False
2021-06-30 12:37:15.361000+00:00    False
2021-06-30 12:37:15.381000+00:00    False
Name: posX, Length: 1535235, dtype: bool

DateTime
2021-05-10 12:13:56.602000+00:00    True
2021-05-10 12:13:56.633000+00:00    True
2021-05-10 12:13:56.676000+00:00    True
2021-05-10 12:13:56.697000+00:00    True
2021-05-10 12:13:56.746000+00:00    True
                                    ...
2021-06-30 12:37:11.081000+00:00    True
2021-06-30 12:37:11.119000+00:00    True
2021-06-30 12:37:11.164000+00:00    True
2021-06-30 12:37:11.205000+00:00    True
2021-06-30 12:37:11.240000+00:00    True
Name: posX, Length: 400527, dtype: bool

DateTime
2021-05-10 12:13:56.584000+00:00        1
2021-05-10 12:13:56.602000+00:00        2
2021-05-10 12:13:56.633000+00:00        2
2021-05-10 12:13:56.676000+00:00        2
2021-05-10 12:13:56.697000+00:00        2
                                    ...
2021-06-30 12:37:15.245000+00:00    16365
2021-06-30 12:37:15.291000+00:00    16365
2021-06-30 12:37:15.323000+00:00    16365
2021-06-30 12:37:15.361000+00:00    16365
2021-06-30 12:37:15.381000+00:00    16365
Name: posX, Length: 1535235, dtype: int32

[DatetimeIndex(['2021-05-10 12:13:56.602000+00:00',
                '2021-05-10 12:13:56.633000+00:00',
                '2021-05-10 12:13:56.676000+00:00',
                '2021-05-10 12:13:56.697000+00:00',
                '2021-05-10 12:13:56.746000+00:00',
                '2021-05-10 12:13:56.800000+00:00',
                '2021-05-10 12:13:56.842000+00:00',
                '2021-05-10 12:13:56.879000+00:00',
                '2021-05-10 12:13:56.914000+00:00',
                '2021-05-10 12:13:56.960000+00:00',
                '2021-05-10 12:13:56.995000+00:00',
                '2021-05-10 12:13:57.037000+00:00',
                '2021-05-10 12:13:57.095000+00:00',
                '2021-05-10 12:13:57.126000+00:00',
                '2021-05-10 12:13:57.161000+00:00',
                '2021-05-10 12:13:57.193000+00:00',
                '2021-05-10 12:13:57.238000+00:00',
                '2021-05-10 12:13:57.290000+00:00',
                '2021-05-10 12:13:57.333000+00:00',
                '2021-05-10 12:13:57.374000+00:00',
                '2021-05-10 12:13:57.415000+00:00',
                '2021-05-10 12:13:57.461000+00:00',
                '2021-05-10 12:13:57.495000+00:00',
                '2021-05-10 12:13:57.524000+00:00',
                '2021-05-10 12:13:57.564000+00:00',
                '2021-05-10 12:13:57.606000+00:00',
                '2021-05-10 12:13:57.646000+00:00',
                '2021-05-10 12:13:57.695000+00:00',
                '2021-05-10 12:13:57.728000+00:00',
                '2021-05-10 12:13:57.772000+00:00',
                '2021-05-10 12:13:57.811000+00:00',
                '2021-05-10 12:13:57.857000+00:00',
                '2021-05-10 12:13:57.906000+00:00',
                '2021-05-10 12:13:57.935000+00:00',
                '2021-05-10 12:13:57.967000+00:00',
                '2021-05-10 12:13:58.003000+00:00',
                '2021-05-10 12:13:58.036000+00:00',
                '2021-05-10 12:13:58.072000+00:00',
                '2021-05-10 12:13:58.112000+00:00',
                '2021-05-10 12:13:58.157000+00:00',
                '2021-05-10 12:13:58.192000+00:00',
                '2021-05-10 12:13:58.232000+00:00',
                '2021-05-10 12:13:58.277000+00:00',
                '2021-05-10 12:13:58.313000+00:00',
                '2021-05-10 12:13:58.344000+00:00',
                '2021-05-10 12:13:58.379000+00:00',
                '2021-05-10 12:13:58.426000+00:00',
                '2021-05-10 12:13:58.457000+00:00',
                '2021-05-10 12:13:58.486000+00:00',
                '2021-05-10 12:13:58.521000+00:00',
                '2021-05-10 12:13:58.567000+00:00',
                '2021-05-10 12:13:58.600000+00:00',
                '2021-05-10 12:13:58.627000+00:00',
                '2021-05-10 12:13:58.658000+00:00',
                '2021-05-10 12:13:58.703000+00:00',
                '2021-05-10 12:13:58.741000+00:00',
                '2021-05-10 12:13:58.776000+00:00',
                '2021-05-10 12:13:58.824000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:07.195000+00:00',
                '2021-05-10 12:14:07.240000+00:00',
                '2021-05-10 12:14:07.283000+00:00',
                '2021-05-10 12:14:07.324000+00:00',
                '2021-05-10 12:14:07.366000+00:00',
                '2021-05-10 12:14:07.408000+00:00',
                '2021-05-10 12:14:07.453000+00:00',
                '2021-05-10 12:14:07.492000+00:00',
                '2021-05-10 12:14:07.525000+00:00',
                '2021-05-10 12:14:07.555000+00:00',
                '2021-05-10 12:14:07.586000+00:00',
                '2021-05-10 12:14:07.618000+00:00',
                '2021-05-10 12:14:07.658000+00:00',
                '2021-05-10 12:14:07.700000+00:00',
                '2021-05-10 12:14:07.740000+00:00',
                '2021-05-10 12:14:07.789000+00:00',
                '2021-05-10 12:14:07.825000+00:00',
                '2021-05-10 12:14:07.860000+00:00',
                '2021-05-10 12:14:07.890000+00:00',
                '2021-05-10 12:14:07.916000+00:00',
                '2021-05-10 12:14:07.949000+00:00',
                '2021-05-10 12:14:07.991000+00:00',
                '2021-05-10 12:14:08.028000+00:00',
                '2021-05-10 12:14:08.060000+00:00',
                '2021-05-10 12:14:08.096000+00:00',
                '2021-05-10 12:14:08.140000+00:00',
                '2021-05-10 12:14:08.173000+00:00',
                '2021-05-10 12:14:08.201000+00:00',
                '2021-05-10 12:14:08.253000+00:00',
                '2021-05-10 12:14:08.286000+00:00',
                '2021-05-10 12:14:08.330000+00:00',
                '2021-05-10 12:14:08.372000+00:00',
                '2021-05-10 12:14:08.429000+00:00',
                '2021-05-10 12:14:08.467000+00:00',
                '2021-05-10 12:14:08.510000+00:00',
                '2021-05-10 12:14:08.540000+00:00',
                '2021-05-10 12:14:08.573000+00:00',
                '2021-05-10 12:14:08.617000+00:00',
                '2021-05-10 12:14:08.658000+00:00',
                '2021-05-10 12:14:08.695000+00:00',
                '2021-05-10 12:14:08.725000+00:00',
                '2021-05-10 12:14:08.774000+00:00',
                '2021-05-10 12:14:08.817000+00:00',
                '2021-05-10 12:14:08.855000+00:00',
                '2021-05-10 12:14:08.897000+00:00',
                '2021-05-10 12:14:08.945000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:14.446000+00:00',
                '2021-05-10 12:14:14.474000+00:00',
                '2021-05-10 12:14:14.511000+00:00',
                '2021-05-10 12:14:14.556000+00:00',
                '2021-05-10 12:14:14.608000+00:00',
                '2021-05-10 12:14:14.643000+00:00',
                '2021-05-10 12:14:14.677000+00:00',
                '2021-05-10 12:14:14.706000+00:00',
                '2021-05-10 12:14:14.746000+00:00',
                '2021-05-10 12:14:14.790000+00:00',
                '2021-05-10 12:14:14.824000+00:00',
                '2021-05-10 12:14:14.854000+00:00',
                '2021-05-10 12:14:14.887000+00:00',
                '2021-05-10 12:14:14.919000+00:00',
                '2021-05-10 12:14:14.951000+00:00',
                '2021-05-10 12:14:14.979000+00:00',
                '2021-05-10 12:14:15.010000+00:00',
                '2021-05-10 12:14:15.045000+00:00',
                '2021-05-10 12:14:15.072000+00:00',
                '2021-05-10 12:14:15.105000+00:00',
                '2021-05-10 12:14:15.153000+00:00',
                '2021-05-10 12:14:15.193000+00:00',
                '2021-05-10 12:14:15.226000+00:00',
                '2021-05-10 12:14:15.268000+00:00',
                '2021-05-10 12:14:15.311000+00:00',
                '2021-05-10 12:14:15.341000+00:00',
                '2021-05-10 12:14:15.373000+00:00',
                '2021-05-10 12:14:15.412000+00:00',
                '2021-05-10 12:14:15.445000+00:00',
                '2021-05-10 12:14:15.491000+00:00',
                '2021-05-10 12:14:15.526000+00:00',
                '2021-05-10 12:14:15.552000+00:00',
                '2021-05-10 12:14:15.582000+00:00',
                '2021-05-10 12:14:15.618000+00:00',
                '2021-05-10 12:14:15.649000+00:00',
                '2021-05-10 12:14:15.692000+00:00',
                '2021-05-10 12:14:15.725000+00:00',
                '2021-05-10 12:14:15.757000+00:00',
                '2021-05-10 12:14:15.792000+00:00',
                '2021-05-10 12:14:15.822000+00:00',
                '2021-05-10 12:14:15.849000+00:00',
                '2021-05-10 12:14:15.892000+00:00',
                '2021-05-10 12:14:15.930000+00:00',
                '2021-05-10 12:14:15.973000+00:00',
                '2021-05-10 12:14:16.009000+00:00',
                '2021-05-10 12:14:16.040000+00:00',
                '2021-05-10 12:14:16.071000+00:00',
                '2021-05-10 12:14:16.107000+00:00',
                '2021-05-10 12:14:16.136000+00:00',
                '2021-05-10 12:14:16.168000+00:00',
                '2021-05-10 12:14:16.201000+00:00',
                '2021-05-10 12:14:16.236000+00:00',
                '2021-05-10 12:14:16.280000+00:00',
                '2021-05-10 12:14:16.312000+00:00',
                '2021-05-10 12:14:16.340000+00:00',
                '2021-05-10 12:14:16.378000+00:00',
                '2021-05-10 12:14:16.421000+00:00',
                '2021-05-10 12:14:16.465000+00:00',
                '2021-05-10 12:14:16.512000+00:00',
                '2021-05-10 12:14:16.542000+00:00',
                '2021-05-10 12:14:16.570000+00:00',
                '2021-05-10 12:14:16.601000+00:00',
                '2021-05-10 12:14:16.638000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:24.045000+00:00',
                '2021-05-10 12:14:24.074000+00:00',
                '2021-05-10 12:14:24.104000+00:00',
                '2021-05-10 12:14:24.147000+00:00',
                '2021-05-10 12:14:24.184000+00:00',
                '2021-05-10 12:14:24.217000+00:00',
                '2021-05-10 12:14:24.262000+00:00',
                '2021-05-10 12:14:24.294000+00:00',
                '2021-05-10 12:14:24.324000+00:00',
                '2021-05-10 12:14:24.364000+00:00',
                '2021-05-10 12:14:24.409000+00:00',
                '2021-05-10 12:14:24.441000+00:00',
                '2021-05-10 12:14:24.497000+00:00',
                '2021-05-10 12:14:24.537000+00:00',
                '2021-05-10 12:14:24.577000+00:00',
                '2021-05-10 12:14:24.609000+00:00',
                '2021-05-10 12:14:24.640000+00:00',
                '2021-05-10 12:14:24.675000+00:00',
                '2021-05-10 12:14:24.709000+00:00',
                '2021-05-10 12:14:24.767000+00:00',
                '2021-05-10 12:14:24.807000+00:00',
                '2021-05-10 12:14:24.845000+00:00',
                '2021-05-10 12:14:24.896000+00:00',
                '2021-05-10 12:14:24.924000+00:00',
                '2021-05-10 12:14:24.959000+00:00',
                '2021-05-10 12:14:25.014000+00:00',
                '2021-05-10 12:14:25.046000+00:00',
                '2021-05-10 12:14:25.091000+00:00',
                '2021-05-10 12:14:25.136000+00:00',
                '2021-05-10 12:14:25.177000+00:00',
                '2021-05-10 12:14:25.209000+00:00',
                '2021-05-10 12:14:25.256000+00:00',
                '2021-05-10 12:14:25.284000+00:00',
                '2021-05-10 12:14:25.341000+00:00',
                '2021-05-10 12:14:25.399000+00:00',
                '2021-05-10 12:14:25.434000+00:00',
                '2021-05-10 12:14:25.473000+00:00',
                '2021-05-10 12:14:25.518000+00:00',
                '2021-05-10 12:14:25.538000+00:00',
                '2021-05-10 12:14:25.580000+00:00',
                '2021-05-10 12:14:25.629000+00:00',
                '2021-05-10 12:14:25.660000+00:00',
                '2021-05-10 12:14:25.689000+00:00',
                '2021-05-10 12:14:25.720000+00:00',
                '2021-05-10 12:14:25.763000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:29.764000+00:00',
                '2021-05-10 12:14:29.796000+00:00',
                '2021-05-10 12:14:29.830000+00:00',
                '2021-05-10 12:14:29.860000+00:00',
                '2021-05-10 12:14:29.904000+00:00',
                '2021-05-10 12:14:29.938000+00:00',
                '2021-05-10 12:14:29.980000+00:00',
                '2021-05-10 12:14:30.024000+00:00',
                '2021-05-10 12:14:30.058000+00:00',
                '2021-05-10 12:14:30.088000+00:00',
                '2021-05-10 12:14:30.133000+00:00',
                '2021-05-10 12:14:30.161000+00:00',
                '2021-05-10 12:14:30.209000+00:00',
                '2021-05-10 12:14:30.239000+00:00',
                '2021-05-10 12:14:30.294000+00:00',
                '2021-05-10 12:14:30.323000+00:00',
                '2021-05-10 12:14:30.356000+00:00',
                '2021-05-10 12:14:30.395000+00:00',
                '2021-05-10 12:14:30.424000+00:00',
                '2021-05-10 12:14:30.454000+00:00',
                '2021-05-10 12:14:30.486000+00:00',
                '2021-05-10 12:14:30.519000+00:00',
                '2021-05-10 12:14:30.557000+00:00',
                '2021-05-10 12:14:30.592000+00:00',
                '2021-05-10 12:14:30.638000+00:00',
                '2021-05-10 12:14:30.677000+00:00',
                '2021-05-10 12:14:30.725000+00:00',
                '2021-05-10 12:14:30.756000+00:00',
                '2021-05-10 12:14:30.801000+00:00',
                '2021-05-10 12:14:30.843000+00:00',
                '2021-05-10 12:14:30.879000+00:00',
                '2021-05-10 12:14:30.923000+00:00',
                '2021-05-10 12:14:30.960000+00:00',
                '2021-05-10 12:14:30.994000+00:00',
                '2021-05-10 12:14:31.039000+00:00',
                '2021-05-10 12:14:31.087000+00:00',
                '2021-05-10 12:14:31.126000+00:00',
                '2021-05-10 12:14:31.158000+00:00',
                '2021-05-10 12:14:31.191000+00:00',
                '2021-05-10 12:14:31.243000+00:00',
                '2021-05-10 12:14:31.273000+00:00',
                '2021-05-10 12:14:31.319000+00:00',
                '2021-05-10 12:14:31.352000+00:00',
                '2021-05-10 12:14:31.397000+00:00',
                '2021-05-10 12:14:31.423000+00:00',
                '2021-05-10 12:14:31.466000+00:00',
                '2021-05-10 12:14:31.509000+00:00',
                '2021-05-10 12:14:31.544000+00:00',
                '2021-05-10 12:14:31.576000+00:00',
                '2021-05-10 12:14:31.609000+00:00',
                '2021-05-10 12:14:31.654000+00:00',
                '2021-05-10 12:14:31.691000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:39.624000+00:00',
                '2021-05-10 12:14:39.670000+00:00',
                '2021-05-10 12:14:39.703000+00:00',
                '2021-05-10 12:14:39.738000+00:00',
                '2021-05-10 12:14:39.778000+00:00',
                '2021-05-10 12:14:39.817000+00:00',
                '2021-05-10 12:14:39.848000+00:00',
                '2021-05-10 12:14:39.881000+00:00',
                '2021-05-10 12:14:39.940000+00:00',
                '2021-05-10 12:14:39.983000+00:00',
                '2021-05-10 12:14:40.026000+00:00',
                '2021-05-10 12:14:40.073000+00:00',
                '2021-05-10 12:14:40.105000+00:00',
                '2021-05-10 12:14:40.135000+00:00',
                '2021-05-10 12:14:40.174000+00:00',
                '2021-05-10 12:14:40.208000+00:00',
                '2021-05-10 12:14:40.253000+00:00',
                '2021-05-10 12:14:40.289000+00:00',
                '2021-05-10 12:14:40.330000+00:00',
                '2021-05-10 12:14:40.373000+00:00',
                '2021-05-10 12:14:40.412000+00:00',
                '2021-05-10 12:14:40.447000+00:00',
                '2021-05-10 12:14:40.492000+00:00',
                '2021-05-10 12:14:40.521000+00:00',
                '2021-05-10 12:14:40.553000+00:00',
                '2021-05-10 12:14:40.582000+00:00',
                '2021-05-10 12:14:40.617000+00:00',
                '2021-05-10 12:14:40.667000+00:00',
                '2021-05-10 12:14:40.693000+00:00',
                '2021-05-10 12:14:40.724000+00:00',
                '2021-05-10 12:14:40.763000+00:00',
                '2021-05-10 12:14:40.791000+00:00',
                '2021-05-10 12:14:40.821000+00:00',
                '2021-05-10 12:14:40.867000+00:00',
                '2021-05-10 12:14:40.890000+00:00',
                '2021-05-10 12:14:40.926000+00:00',
                '2021-05-10 12:14:40.961000+00:00',
                '2021-05-10 12:14:40.993000+00:00',
                '2021-05-10 12:14:41.037000+00:00',
                '2021-05-10 12:14:41.069000+00:00',
                '2021-05-10 12:14:41.117000+00:00',
                '2021-05-10 12:14:41.165000+00:00',
                '2021-05-10 12:14:41.199000+00:00',
                '2021-05-10 12:14:41.238000+00:00',
                '2021-05-10 12:14:41.281000+00:00',
                '2021-05-10 12:14:41.324000+00:00',
                '2021-05-10 12:14:41.366000+00:00',
                '2021-05-10 12:14:41.388000+00:00',
                '2021-05-10 12:14:41.426000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:49.247000+00:00',
                '2021-05-10 12:14:49.278000+00:00',
                '2021-05-10 12:14:49.308000+00:00',
                '2021-05-10 12:14:49.353000+00:00',
                '2021-05-10 12:14:49.403000+00:00',
                '2021-05-10 12:14:49.445000+00:00',
                '2021-05-10 12:14:49.478000+00:00',
                '2021-05-10 12:14:49.522000+00:00',
                '2021-05-10 12:14:49.571000+00:00',
                '2021-05-10 12:14:49.624000+00:00',
                '2021-05-10 12:14:49.653000+00:00',
                '2021-05-10 12:14:49.683000+00:00',
                '2021-05-10 12:14:49.724000+00:00',
                '2021-05-10 12:14:49.790000+00:00',
                '2021-05-10 12:14:49.824000+00:00',
                '2021-05-10 12:14:49.870000+00:00',
                '2021-05-10 12:14:49.899000+00:00',
                '2021-05-10 12:14:49.933000+00:00',
                '2021-05-10 12:14:49.978000+00:00',
                '2021-05-10 12:14:50.012000+00:00',
                '2021-05-10 12:14:50.056000+00:00',
                '2021-05-10 12:14:50.090000+00:00',
                '2021-05-10 12:14:50.126000+00:00',
                '2021-05-10 12:14:50.165000+00:00',
                '2021-05-10 12:14:50.205000+00:00',
                '2021-05-10 12:14:50.232000+00:00',
                '2021-05-10 12:14:50.263000+00:00',
                '2021-05-10 12:14:50.325000+00:00',
                '2021-05-10 12:14:50.358000+00:00',
                '2021-05-10 12:14:50.403000+00:00',
                '2021-05-10 12:14:50.460000+00:00',
                '2021-05-10 12:14:50.485000+00:00'],
               dtype='datetime64[ns, UTC]', name='DateTime', freq=None),
 DatetimeIndex(['2021-05-10 12:14:57.107000+00:00',
                '2021-05-10 12:14:57.142000+00:00',
                '2021-05-10 12:14:57.176000+00:00',
                '2021-05-10 12:14:57.210000+00:00',
                '2021-05-10 12:14:57.240000+00:00',
                '2021-05-10 12:14:57.274000+00:00',
                '2021-05-10 12:14:57.316000+00:00',
                '2021-05-10 12:14:57.373000+00:00',
                '2021-05-10 12:14:57.423000+00:00',
                '2021-05-10 12:14:57.454000+00:00',
                '2021-05-10 12:14:57.482000+00:00',
                '2021-05-10 12:14:57.515000+00:00',
                '2021-05-10 12:14:57.567000+00:00',
                '2021-05-10 12:14:57.601000+00:00',
                '2021-05-10 12:14:57.653000+00:00',
                '2021-05-10 12:14:57.687000+00:00',
                '2021-05-10 12:14:57.717000+00:00',
                '2021-05-10 12:14:57.750000+00:00',
                '2021-05-10 12:14:57.786000+00:00',
                '2021-05-10 12:14:57.827000+00:00',
                '2021-05-10 12:14:57.854000+00:00',
                '2021-05-10 12:14:57.906000+00:00',
                '2021-05-10 12:14:57.934000+00:00',
                '2021-05-10 12:14:57.975000+00:00',
                '2021-05-10 12:14:58.019000+00:00',
                '2021-05-10 12:14:58.064000+00:00',
                '2021-05-10 12:14:58.106000+00:00',
                '2021-05-10 12:14:58.141000+00:00',
                '2021-05-10 12:14:58.180000+00:00',

Anzahl der entfernten Nullwerte: 401213

,Unnamed: 0,SampleIdx_global,SampleIdx_Proband,State,mappingMethod,Task,TargetLayers,NumLayers,Trial,posX,...,posZ,TimeStamp,iteractionType,currentLayer,Proband,shifted,Result,Block,Target,Target_Relative
0,1189494,1855631,28737,SUBTASK_STATE,widening,4,"['17', '5', '1', '9', '14']",18,3,START,...,NaN,NaN,NaN,NaN,18,22.0,START,2,9,0.5
1,1189495,1855632,28738,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.195627853,...,-0.769736648,637598980897781800,1,13,18,22.0,COMPLETED,2,9,0.5
2,1189496,1855633,28739,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.1848301,...,-0.8210525,637598980898231700,1,15,18,22.0,COMPLETED,2,9,0.5
3,1189497,1855634,28740,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.1848301,...,-0.8210525,637598980898619400,1,16,18,22.0,COMPLETED,2,9,0.5
4,1189498,1855635,28741,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.17597948,...,-0.8565788,637598980898949400,1,16,18,22.0,COMPLETED,2,9,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,1199048,1865185,38291,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.3192707,...,-0.335526258,637598984549783700,1,9,18,22.0,COMPLETED,2,9,0.5
199,1199049,1865186,38292,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.323519021,...,-0.339473575,637598984550213600,1,9,18,22.0,COMPLETED,2,9,0.5
200,1199050,1865187,38293,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.323519021,...,-0.339473575,637598984550603800,1,9,18,22.0,COMPLETED,2,9,0.5
201,1199051,1865188,38294,INTERACTION,widening,4,"['17', '5', '1', '9', '14']",18,3,0.323519021,...,-0.339473575,637598984550873600,1,9,18,22.0,COMPLETED,2,9,0.5
202,1199052,1865189,38295,SUBTASK_STATE,widening,4,"['17', '5', '1', '9', '14']",18,3,COMPLETED,...,NaN,NaN,NaN,NaN,18,22.0,COMPLETED,2,9,0.5