In [24]:
# Imports / global contants

# csv Dateien sind im Verzeichnis ../data zu finden

import pandas as pd
import glob
import os
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from matplotlib import figure
import math
import numpy as np
import seaborn as sns
from scipy.misc import electrocardiogram
from scipy.signal import find_peaks
import gc
import pylab

import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio

from pandas.plotting import parallel_coordinates

%matplotlib inline

timeFormat = "%Y-%m-%dT%H:%M:%S.%fZ"

original = "../export/"

export = "../diss/csv/"
export_img = "../export/img/"
export_interactions = "../export/interaction/"

path = "../data/"

gtv_colormap = {1: 'rgb(54, 161, 185)', 2: 'rgb(0, 44, 61)', 3: 'rgb(233, 71, 74)'}
plot_bgcolor = 'rgba(239, 240, 231,.7)'

numSamplesForRemoval = 300

In [25]:
df_times = pd.read_csv(rf'{original}times_removed-inactive-{numSamplesForRemoval}.csv', sep= ";")

display(df_times)

df_grouped = df_times.groupby(['Proband', 'MappingMethod', 'NumLayers'])['Duration_CleanedUp_Computed'].mean().reset_index()

df_pivot = df_grouped.pivot(index='Proband', columns=['MappingMethod', 'NumLayers'], values='Duration_CleanedUp_Computed')

df_pivot.columns = [f"{m}_{l}" for m, l in df_pivot.columns]

df_times_spss = df_pivot.reset_index()

display(df_times_spss)

df_times_spss.to_csv(rf'{export}times_removed-inactive-{numSamplesForRemoval}_rmANOVA-mean.csv', sep=";")

,Unnamed: 0.1,Unnamed: 0,MappingMethod,FrameNumber_Start,FrameNumber_Finish,Block,Task,Trial,NumLayers,Target,...,Result,Proband,FrameRate_1,TrialNumber,NumFrames_CleanedUp,NumFrames_Difference,Duration_CleanedUp_Interpolated,Duration_Difference_Interpolated,Duration_CleanedUp_Computed,Duration_Difference_Computed
0,0,0,direct,65,242,1,1,0,12,3,...,COMPLETED,23,26.339286,0,177,0,4.662054,2.057946,6.720,0.0
1,1,1,direct,295,547,1,1,1,12,11,...,COMPLETED,23,26.258206,1,252,0,6.617068,2.979932,9.597,0.0
2,2,2,direct,604,808,1,1,2,12,9,...,COMPLETED,23,26.600600,2,204,0,5.426522,2.242478,7.669,0.0
3,3,3,direct,849,1050,1,1,3,12,6,...,TERMINATED,23,26.675514,3,201,0,5.361778,2.173222,7.535,0.0
4,4,4,direct,1114,1350,1,1,4,12,1,...,COMPLETED,23,25.962596,4,236,0,6.127173,2.962827,9.090,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6205,6205,6205,widening,88872,89061,3,18,0,15,8,...,COMPLETED,12,26.984580,265,189,0,5.100086,1.903914,7.004,0.0
6206,6206,6206,widening,89096,89278,3,18,1,15,11,...,COMPLETED,12,27.790502,266,182,0,5.057871,1.491129,6.549,0.0
6207,6207,6207,widening,89320,89518,3,18,2,15,14,...,TERMINATED,12,26.811104,267,198,0,5.308599,2.076401,7.385,0.0
6208,6208,6208,widening,89570,89735,3,18,3,15,4,...,TERMINATED,12,28.004073,268,165,0,4.620672,1.271328,5.892,0.0
6209,6209,6209,widening,89793,90028,3,18,4,15,1,...,COMPLETED,12,26.943362,269,235,0,6.331690,2.390310,8.722,0.0

,Proband,densening_6,densening_9,densening_12,densening_15,densening_18,densening_21,direct_6,direct_9,direct_12,direct_15,direct_18,direct_21,widening_6,widening_9,widening_12,widening_15,widening_18,widening_21
0,1,5.503000,5.681733,6.774133,7.501067,7.800000,7.823467,5.474067,7.965800,6.522867,7.725067,7.313400,8.377133,4.898267,5.943867,6.570333,8.352467,9.212000,7.928400
1,2,6.116733,8.707600,8.068267,9.169467,9.402467,9.513667,5.806733,8.428400,9.179733,8.124467,9.288200,10.309667,6.534933,7.270800,8.127067,7.959067,9.512800,10.312200
2,3,5.279600,6.758200,6.441533,10.562667,13.937867,12.973600,4.477467,6.403800,7.860467,8.763133,15.435600,13.191533,4.801467,6.483600,8.078333,10.419333,9.423667,11.320200
3,4,5.897533,8.604733,8.753867,16.742733,20.282733,17.128533,5.962933,7.053667,9.829400,12.189000,20.187000,18.681400,6.504800,9.495533,11.448467,15.385400,13.136533,19.319533
4,5,6.160467,6.204933,8.062400,8.702667,8.945200,8.833933,4.982200,6.220733,7.130533,7.838667,8.723267,8.825933,5.401067,5.791133,7.229067,7.929533,8.697133,8.587467
5,6,7.429467,7.205667,8.819200,10.066133,7.997333,9.863400,6.024667,6.693933,7.228867,8.593933,8.142933,9.297800,6.336133,8.193267,8.902600,8.511000,8.585733,9.065533
6,7,6.549867,6.806133,7.375733,8.017400,8.873200,9.502267,5.712933,7.530400,8.757267,9.014533,9.188800,11.073267,5.881667,8.059733,7.935933,9.779067,9.316667,10.124533
7,8,8.642133,11.060000,9.774467,10.755400,10.130867,11.820067,6.031267,7.845333,7.334400,12.126200,10.650200,11.256667,7.496867,7.679400,9.404933,9.338867,11.260733,14.102200
8,9,8.503600,10.601600,8.235067,12.870667,11.514467,10.607200,6.460200,6.546000,8.186533,9.734800,9.628600,8.903400,6.698733,7.314133,9.544600,11.707400,12.372533,12.303000
9,10,4.882533,5.718333,7.603600,9.013533,8.870400,12.860400,4.656267,5.372400,5.647000,6.113267,11.147333,11.073533,4.975400,5.477600,7.948267,6.545200,9.710400,7.416867
10,11,6.955200,5.378867,6.920600,8.314667,9.057200,9.716533,5.092400,6.567467,7.488800,9.362000,9.259467,9.253467,5.437667,5.585667,7.768067,7.549467,9.150667,10.154533
11,12,5.940667,6.553667,7.645200,7.789667,8.228467,8.324000,6.469133,7.864933,7.247400,9.355600,8.675800,9.831867,5.372067,6.805267,7.405000,7.516400,8.551733,8.562333
12,13,6.903067,7.378067,10.966067,9.143000,11.681133,12.177667,6.246200,7.463467,8.870067,9.584867,10.023400,8.674467,5.430600,7.847000,9.122733,11.059933,12.396133,13.038667
13,14,5.332133,6.691267,7.678933,8.389933,9.047067,9.880467,6.018333,7.323667,7.487267,9.807867,9.996533,11.079133,5.040200,8.034400,7.282600,9.152933,9.251000,14.016000
14,15,6.653267,8.997000,9.360267,9.595600,10.167867,11.681000,5.698467,7.503067,8.426667,9.271400,8.703600,9.707000,6.778133,7.987667,7.967733,9.143333,9.570733,9.387867
15,16,5.872400,7.848667,7.684733,9.683867,10.713400,9.230933,6.483067,7.488800,10.563600,10.994600,11.828400,14.491400,6.053733,7.029867,10.544533,13.541000,12.095000,18.815733
16,17,6.144200,6.350400,6.837400,7.580600,7.505733,7.988400,5.481467,6.060333,6.897200,7.294067,7.465867,7.292267,5.879667,8.690533,6.774800,8.338200,6.664733,8.072267
17,18,5.921867,6.643000,7.792467,7.596733,9.642133,8.660467,6.039800,6.292933,8.326400,7.241733,8.356733,8.072333,5.031000,7.249733,7.390600,8.013267,8.206733,8.815800
18,19,6.346733,8.477133,9.653467,10.263933,11.556467,10.357133,6.066867,7.392667,8.575200,10.246667,8.919667,10.445800,7.336133,6.759400,7.813467,8.752667,10.559067,9.426733
19,20,5.555533,6.665600,6.804067,8.049733,9.807733,8.256267,5.835133,6.931533,7.513800,7.730400,8.742800,9.034867,5.895667,6.832733,7.610400,8.031267,11.766067,11.315133
20,22,6.614933,6.722467,8.436133,7.877333,8.480600,8.967733,5.843733,6.942533,7.723200,8.708933,8.366867,8.506933,5.200333,6.107867,8.617467,7.427467,8.361800,9.636000
21,23,5.811533,7.168000,7.532400,7.959333,8.441933,8.930800,5.700667,6.770400,7.065333,8.842267,7.859067,8.492467,5.526800,6.441733,8.025733,8.228800,10.006400,11.425400
22,24,6.062400,7.891067,8.627333,7.879267,8.914133,11.098067,5.306200,6.126667,7.681000,7.770200,7.763867,8.811000,5.397133,5.783200,7.258667,6.632800,7.237867,8.721067

In [ ]:
df_times = pd.read_csv(rf'{original}times.csv', sep= ";")

display(df_times)

df_grouped = df_times.groupby(['Proband', 'MappingMethod', 'NumLayers'])['Duration'].mean().reset_index()

df_pivot = df_grouped.pivot(index='Proband', columns=['MappingMethod', 'NumLayers'], values='Duration')

df_pivot.columns = [f"{m}_{l}" for m, l in df_pivot.columns]

df_times_spss = df_pivot.reset_index()

display(df_times_spss)

# df_times_spss.to_csv(rf'{export}times_rmANOVA-mean.csv', sep=";")

,Unnamed: 0,MappingMethod,FrameNumber_Start,FrameNumber_Finish,Block,Task,Trial,NumLayers,Target,Target_Relative,DateTime_Start,DateTime_Finish,Duration,NumFrames,Result,Proband,FrameRate_1
0,0,direct,65,242,1,1,0,12,3,0.250000,2021-06-29T07:19:27.465Z,2021-06-29T07:19:34.185Z,6.720,177,COMPLETED,23,26.339286
1,1,direct,295,547,1,1,1,12,11,0.916667,2021-06-29T07:19:36.096Z,2021-06-29T07:19:45.693Z,9.597,252,COMPLETED,23,26.258206
2,2,direct,604,808,1,1,2,12,9,0.750000,2021-06-29T07:19:47.749Z,2021-06-29T07:19:55.418Z,7.669,204,COMPLETED,23,26.600600
3,3,direct,849,1050,1,1,3,12,6,0.500000,2021-06-29T07:19:56.961Z,2021-06-29T07:20:04.496Z,7.535,201,TERMINATED,23,26.675514
4,4,direct,1114,1350,1,1,4,12,1,0.083333,2021-06-29T07:20:06.928Z,2021-06-29T07:20:16.018Z,9.090,236,COMPLETED,23,25.962596
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6205,6205,widening,88872,89061,3,18,0,15,8,0.533333,2021-05-31T10:18:07.589Z,2021-05-31T10:18:14.593Z,7.004,189,COMPLETED,12,26.984580
6206,6206,widening,89096,89278,3,18,1,15,11,0.733333,2021-05-31T10:18:15.806Z,2021-05-31T10:18:22.355Z,6.549,182,COMPLETED,12,27.790502
6207,6207,widening,89320,89518,3,18,2,15,14,0.933333,2021-05-31T10:18:23.773Z,2021-05-31T10:18:31.158Z,7.385,198,TERMINATED,12,26.811104
6208,6208,widening,89570,89735,3,18,3,15,4,0.266667,2021-05-31T10:18:32.948Z,2021-05-31T10:18:38.840Z,5.892,165,TERMINATED,12,28.004073
6209,6209,widening,89793,90028,3,18,4,15,1,0.066667,2021-05-31T10:18:40.914Z,2021-05-31T10:18:49.636Z,8.722,235,COMPLETED,12,26.943362

,Proband,densening_6,densening_9,densening_12,densening_15,densening_18,densening_21,direct_6,direct_9,direct_12,direct_15,direct_18,direct_21,widening_6,widening_9,widening_12,widening_15,widening_18,widening_21
0,1,5.503000,5.681733,6.774133,7.501067,7.800000,7.823467,5.474067,7.965800,7.479267,7.725067,7.313400,11.810933,4.898267,7.539800,6.570333,8.352467,9.212000,7.928400
1,2,6.116733,8.707600,8.068267,11.448600,12.199733,12.649133,5.806733,8.428400,10.868267,8.124467,11.269933,10.309667,6.534933,7.270800,10.945733,9.365267,12.161400,11.318467
2,3,5.279600,6.758200,6.441533,10.562667,13.937867,12.973600,6.139133,6.403800,7.860467,8.763133,15.435600,13.191533,4.801467,6.483600,8.078333,10.419333,9.423667,11.320200
3,4,5.897533,8.604733,8.753867,16.742733,20.282733,17.128533,5.962933,7.053667,9.829400,12.189000,20.187000,18.681400,6.504800,10.509133,11.448467,15.385400,13.136533,19.319533
4,5,6.160467,6.204933,8.062400,8.702667,8.945200,8.833933,4.982200,6.220733,7.130533,7.838667,8.723267,8.825933,5.401067,5.791133,7.229067,7.929533,8.697133,8.587467
5,6,7.429467,8.854133,8.819200,11.073400,7.997333,9.863400,6.024667,6.693933,8.068867,8.593933,9.074867,12.111667,6.336133,27.160733,8.902600,8.511000,10.391267,12.385200
6,7,14.160867,6.806133,7.375733,9.106533,8.873200,9.502267,5.712933,10.112067,8.757267,9.014533,9.188800,11.073267,5.881667,8.059733,12.148533,9.779067,9.316667,11.321200
7,8,8.642133,12.105800,9.774467,10.755400,11.471867,12.702000,6.031267,7.845333,7.334400,14.230333,11.677933,32.997733,12.297000,8.879467,10.989467,11.460400,11.260733,17.697067
8,9,8.503600,10.601600,8.235067,12.870667,11.514467,10.607200,6.460200,6.546000,8.186533,11.273667,9.628600,8.903400,6.698733,7.314133,9.544600,11.707400,13.528600,12.303000
9,10,4.882533,5.718333,7.603600,9.013533,8.870400,12.860400,4.656267,22.784067,5.647000,6.113267,11.147333,11.073533,6.282267,5.477600,7.948267,6.545200,9.710400,15.973067
10,11,6.955200,5.378867,6.920600,8.314667,24.681267,9.716533,5.092400,6.567467,7.488800,9.362000,9.259467,9.253467,5.437667,5.585667,7.768067,7.549467,9.150667,10.154533
11,12,5.940667,6.553667,7.645200,7.789667,8.228467,8.324000,6.469133,7.864933,7.247400,9.355600,8.675800,9.831867,5.372067,6.805267,7.405000,7.516400,8.551733,8.562333
12,13,6.903067,7.378067,21.376600,9.143000,11.681133,12.177667,26.255267,7.463467,8.870067,12.963800,10.023400,10.688933,5.430600,8.719000,9.122733,11.059933,19.919067,15.821667
13,14,6.493133,6.691267,7.678933,8.389933,9.047067,9.880467,6.018333,7.323667,7.487267,9.807867,9.996533,11.079133,5.040200,8.034400,7.282600,10.090400,9.251000,14.016000
14,15,6.653267,33.319867,10.448133,9.595600,10.167867,11.681000,5.698467,8.642333,8.426667,10.368800,8.703600,16.422333,6.778133,8.841933,7.967733,11.649733,10.670200,10.454133
15,16,5.872400,7.848667,7.684733,9.683867,10.713400,9.230933,6.483067,7.488800,10.563600,25.668200,11.828400,14.491400,6.053733,7.029867,10.544533,13.541000,12.095000,18.815733
16,17,6.144200,6.350400,6.837400,7.580600,7.505733,7.988400,5.481467,6.060333,6.897200,8.296733,7.465867,7.292267,8.480800,8.690533,6.774800,8.338200,6.664733,9.357200
17,18,25.693400,6.643000,11.826533,8.403933,12.032333,9.649467,6.039800,6.292933,8.326400,7.241733,8.356733,8.072333,5.031000,7.249733,7.390600,8.013267,32.054933,8.815800
18,19,6.346733,8.477133,9.653467,10.263933,11.556467,10.357133,6.066867,23.976333,8.575200,14.092733,8.919667,10.445800,7.336133,6.759400,7.813467,8.752667,10.559067,11.127933
19,20,5.555533,6.665600,6.804067,8.049733,9.807733,8.256267,5.835133,6.931533,7.513800,7.730400,8.742800,9.034867,5.895667,6.832733,7.610400,8.031267,11.766067,11.315133
20,22,6.614933,6.722467,8.436133,7.877333,8.480600,8.967733,5.843733,6.942533,7.723200,8.708933,8.366867,8.506933,5.200333,6.107867,8.617467,7.427467,8.361800,9.636000
21,23,5.811533,7.168000,7.532400,7.959333,8.441933,8.930800,5.700667,6.770400,7.065333,8.842267,7.859067,8.492467,5.526800,6.441733,8.025733,8.228800,10.006400,11.425400
22,24,6.062400,7.891067,8.627333,7.879267,8.914133,11.098067,5.306200,6.126667,7.681000,7.770200,7.763867,8.811000,5.397133,5.783200,7.258667,6.632800,7.237867,8.721067

In [ ]:
df_times = pd.read_csv(rf'{original}times.csv', sep= ";")

df_times['Measure'] = df_times.groupby(['Proband', 'MappingMethod', 'NumLayers']).cumcount() + 1

display(df_times)

df_pivot = df_times.pivot_table(
    index='Proband',
    columns=['Measure', 'MappingMethod', 'NumLayers'],
    values='Duration'
)

df_pivot.columns = [f"{m}_{l}_{t}" for m, l, t in df_pivot.columns]

df_times_spss2 = df_pivot.reset_index()

display(df_times_spss2)

# df_times_spss2.to_csv(rf'{export}times_rmANOVA.csv', sep=";")

,Unnamed: 0,MappingMethod,FrameNumber_Start,FrameNumber_Finish,Block,Task,Trial,NumLayers,Target,Target_Relative,DateTime_Start,DateTime_Finish,Duration,NumFrames,Result,Proband,FrameRate_1,Measure
0,0,direct,65,242,1,1,0,12,3,0.250000,2021-06-29T07:19:27.465Z,2021-06-29T07:19:34.185Z,6.720,177,COMPLETED,23,26.339286,1
1,1,direct,295,547,1,1,1,12,11,0.916667,2021-06-29T07:19:36.096Z,2021-06-29T07:19:45.693Z,9.597,252,COMPLETED,23,26.258206,2
2,2,direct,604,808,1,1,2,12,9,0.750000,2021-06-29T07:19:47.749Z,2021-06-29T07:19:55.418Z,7.669,204,COMPLETED,23,26.600600,3
3,3,direct,849,1050,1,1,3,12,6,0.500000,2021-06-29T07:19:56.961Z,2021-06-29T07:20:04.496Z,7.535,201,TERMINATED,23,26.675514,4
4,4,direct,1114,1350,1,1,4,12,1,0.083333,2021-06-29T07:20:06.928Z,2021-06-29T07:20:16.018Z,9.090,236,COMPLETED,23,25.962596,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6205,6205,widening,88872,89061,3,18,0,15,8,0.533333,2021-05-31T10:18:07.589Z,2021-05-31T10:18:14.593Z,7.004,189,COMPLETED,12,26.984580,11
6206,6206,widening,89096,89278,3,18,1,15,11,0.733333,2021-05-31T10:18:15.806Z,2021-05-31T10:18:22.355Z,6.549,182,COMPLETED,12,27.790502,12
6207,6207,widening,89320,89518,3,18,2,15,14,0.933333,2021-05-31T10:18:23.773Z,2021-05-31T10:18:31.158Z,7.385,198,TERMINATED,12,26.811104,13
6208,6208,widening,89570,89735,3,18,3,15,4,0.266667,2021-05-31T10:18:32.948Z,2021-05-31T10:18:38.840Z,5.892,165,TERMINATED,12,28.004073,14
6209,6209,widening,89793,90028,3,18,4,15,1,0.066667,2021-05-31T10:18:40.914Z,2021-05-31T10:18:49.636Z,8.722,235,COMPLETED,12,26.943362,15

,Proband,1_ densening_6,1_ densening_9,1_ densening_12,1_ densening_15,1_ densening_18,1_ densening_21,1_ direct_6,1_ direct_9,1_ direct_12,...,15_ direct_12,15_ direct_15,15_ direct_18,15_ direct_21,15_ widening_6,15_ widening_9,15_ widening_12,15_ widening_15,15_ widening_18,15_ widening_21
0,1,5.253,6.209,7.046,8.298,6.770,7.254,7.368,6.978,6.645,...,7.861,6.198,7.974,7.777,5.917,7.507,5.973,7.479,9.905,7.309
1,2,5.871,12.110,12.799,9.337,9.220,5.272,6.061,9.415,8.308,...,9.385,9.962,10.491,14.228,7.628,7.535,6.333,7.432,49.389,20.144
2,3,9.699,7.336,9.165,5.902,17.872,5.793,28.750,4.845,6.833,...,14.458,15.887,17.365,6.925,3.004,5.805,10.616,7.682,7.147,6.951
3,4,7.995,19.506,6.351,13.717,25.701,16.241,5.754,8.051,8.368,...,8.357,15.585,7.935,8.443,6.069,7.898,10.611,10.822,8.707,14.274
4,5,4.402,6.206,7.662,8.144,6.270,6.160,3.886,5.193,8.626,...,5.260,6.992,7.530,8.028,5.812,6.828,6.768,6.574,10.862,11.253
5,6,6.433,7.937,15.800,13.040,7.659,9.423,4.526,6.554,8.614,...,6.970,14.024,6.890,6.759,4.656,14.171,10.047,7.437,6.469,7.052
6,7,7.534,7.483,8.514,8.631,8.761,8.890,6.137,42.485,10.043,...,6.693,2.896,8.886,15.833,6.476,11.715,6.169,11.183,9.339,8.083
7,8,9.659,10.424,21.631,12.134,14.253,11.642,7.827,6.578,6.528,...,7.727,12.983,12.741,10.135,3.762,6.942,8.730,9.365,9.759,25.176
8,9,7.597,25.974,8.393,10.918,6.185,17.886,14.081,4.011,9.471,...,9.038,6.363,8.001,7.109,5.284,6.593,7.866,11.976,9.602,5.451
9,10,2.562,4.503,4.673,7.278,5.450,9.862,2.435,264.491,3.840,...,3.719,7.584,43.499,7.689,5.408,5.965,4.791,6.738,6.791,7.115
10,11,5.486,6.367,5.473,4.456,242.304,8.675,6.093,10.099,6.963,...,8.727,7.425,4.782,8.981,4.580,4.938,6.689,6.225,10.636,19.305
11,12,4.231,7.461,9.180,6.186,8.266,7.103,6.392,10.484,5.267,...,6.102,7.765,7.260,6.391,5.395,6.853,8.733,8.722,4.966,10.679
12,13,5.618,8.477,6.935,13.042,17.595,8.331,307.572,16.494,6.412,...,7.473,11.032,8.626,8.835,5.067,10.780,6.868,7.930,10.681,18.849
13,14,4.689,5.453,8.715,9.196,7.949,15.573,6.182,6.075,6.520,...,5.726,5.548,10.211,8.091,4.071,3.477,3.643,7.271,13.604,6.007
14,15,7.260,375.574,24.060,7.239,7.920,12.412,4.751,10.636,9.578,...,10.065,20.222,8.780,10.105,8.758,5.561,6.588,8.909,9.290,10.039
15,16,4.231,15.876,7.745,7.193,5.019,8.432,6.794,8.004,6.704,...,5.882,10.152,9.021,11.481,8.273,4.073,28.261,12.314,6.959,7.478
16,17,6.466,6.601,7.794,11.584,8.156,10.204,5.201,7.427,5.962,...,8.232,7.724,6.727,7.778,9.669,14.033,7.218,6.641,7.066,6.908
17,18,6.187,4.944,8.117,8.999,17.903,16.397,5.445,5.792,6.705,...,6.570,9.006,6.900,8.276,4.373,7.221,5.596,13.471,6.732,5.300
18,19,4.689,11.994,16.322,8.647,13.832,6.164,5.253,8.414,7.448,...,7.294,9.182,9.919,15.627,6.288,5.852,6.815,6.966,10.368,8.374
19,20,5.649,6.027,8.313,7.321,9.078,9.931,5.024,11.840,8.679,...,5.893,4.745,6.938,6.936,5.739,6.147,5.790,6.774,48.935,14.712
20,22,5.510,6.697,8.451,8.677,12.498,6.513,6.350,6.689,7.670,...,8.469,10.666,7.215,12.328,3.512,9.078,11.210,6.311,7.486,7.974
21,23,5.988,8.397,8.327,10.521,8.457,7.216,3.831,6.437,6.720,...,6.676,10.906,6.369,7.463,5.443,5.580,7.755,6.395,7.299,7.133
22,24,9.020,9.766,8.232,9.223,7.536,7.049,2.643,5.206,7.469,...,6.658,7.218,7.380,6.418,5.088,5.683,5.323,6.698,5.356,6.644

In [ ]:
df_times = pd.read_csv(rf'{original}times_removed-inactive-{numSamplesForRemoval}.csv', sep= ";")

df_times['Measure'] = df_times.groupby(['Proband', 'MappingMethod', 'NumLayers']).cumcount() + 1

display(df_times)

df_pivot = df_times.pivot_table(
    index='Proband',
    columns=['Measure', 'MappingMethod', 'NumLayers'],
    values='Duration_CleanedUp_Computed'
)

df_pivot.columns = [f"{m}_{l}_{t}" for m, l, t in df_pivot.columns]

df_times_spss2 = df_pivot.reset_index()

display(df_times_spss2)

# df_times_spss2.to_csv(rf'{export}times_removed-inactive-{numSamplesForRemoval}_rmANOVA.csv', sep=";")

,Unnamed: 0.1,Unnamed: 0,MappingMethod,FrameNumber_Start,FrameNumber_Finish,Block,Task,Trial,NumLayers,Target,...,Proband,FrameRate_1,TrialNumber,NumFrames_CleanedUp,NumFrames_Difference,Duration_CleanedUp_Interpolated,Duration_Difference_Interpolated,Duration_CleanedUp_Computed,Duration_Difference_Computed,Measure
0,0,0,direct,65,242,1,1,0,12,3,...,23,26.339286,0,177,0,4.662054,2.057946,6.720,0.0,1
1,1,1,direct,295,547,1,1,1,12,11,...,23,26.258206,1,252,0,6.617068,2.979932,9.597,0.0,2
2,2,2,direct,604,808,1,1,2,12,9,...,23,26.600600,2,204,0,5.426522,2.242478,7.669,0.0,3
3,3,3,direct,849,1050,1,1,3,12,6,...,23,26.675514,3,201,0,5.361778,2.173222,7.535,0.0,4
4,4,4,direct,1114,1350,1,1,4,12,1,...,23,25.962596,4,236,0,6.127173,2.962827,9.090,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6205,6205,6205,widening,88872,89061,3,18,0,15,8,...,12,26.984580,265,189,0,5.100086,1.903914,7.004,0.0,11
6206,6206,6206,widening,89096,89278,3,18,1,15,11,...,12,27.790502,266,182,0,5.057871,1.491129,6.549,0.0,12
6207,6207,6207,widening,89320,89518,3,18,2,15,14,...,12,26.811104,267,198,0,5.308599,2.076401,7.385,0.0,13
6208,6208,6208,widening,89570,89735,3,18,3,15,4,...,12,28.004073,268,165,0,4.620672,1.271328,5.892,0.0,14
6209,6209,6209,widening,89793,90028,3,18,4,15,1,...,12,26.943362,269,235,0,6.331690,2.390310,8.722,0.0,15

,Proband,1_ densening_6,1_ densening_9,1_ densening_12,1_ densening_15,1_ densening_18,1_ densening_21,1_ direct_6,1_ direct_9,1_ direct_12,...,15_ direct_12,15_ direct_15,15_ direct_18,15_ direct_21,15_ widening_6,15_ widening_9,15_ widening_12,15_ widening_15,15_ widening_18,15_ widening_21
0,1,5.253,6.209,7.046,8.298,6.770,7.254,7.368,6.978,6.645,...,7.861,6.198,7.974,7.777,5.917,7.507,5.973,7.479,9.905,7.309
1,2,5.871,12.110,12.799,9.337,9.220,5.272,6.061,9.415,8.308,...,9.385,9.962,10.491,14.228,7.628,7.535,6.333,7.432,9.660,20.144
2,3,9.699,7.336,9.165,5.902,17.872,5.793,3.825,4.845,6.833,...,14.458,15.887,17.365,6.925,3.004,5.805,10.616,7.682,7.147,6.951
3,4,7.995,19.506,6.351,13.717,25.701,16.241,5.754,8.051,8.368,...,8.357,15.585,7.935,8.443,6.069,7.898,10.611,10.822,8.707,14.274
4,5,4.402,6.206,7.662,8.144,6.270,6.160,3.886,5.193,8.626,...,5.260,6.992,7.530,8.028,5.812,6.828,6.768,6.574,10.862,11.253
5,6,6.433,7.937,15.800,13.040,7.659,9.423,4.526,6.554,8.614,...,6.970,14.024,6.890,6.759,4.656,14.171,10.047,7.437,6.469,7.052
6,7,7.534,7.483,8.514,8.631,8.761,8.890,6.137,3.760,10.043,...,6.693,2.896,8.886,15.833,6.476,11.715,6.169,11.183,9.339,8.083
7,8,9.659,10.424,21.631,12.134,14.253,11.642,7.827,6.578,6.528,...,7.727,12.983,12.741,10.135,3.762,6.942,8.730,9.365,9.759,25.176
8,9,7.597,25.974,8.393,10.918,6.185,17.886,14.081,4.011,9.471,...,9.038,6.363,8.001,7.109,5.284,6.593,7.866,11.976,9.602,5.451
9,10,2.562,4.503,4.673,7.278,5.450,9.862,2.435,3.316,3.840,...,3.719,7.584,43.499,7.689,5.408,5.965,4.791,6.738,6.791,7.115
10,11,5.486,6.367,5.473,4.456,7.943,8.675,6.093,10.099,6.963,...,8.727,7.425,4.782,8.981,4.580,4.938,6.689,6.225,10.636,19.305
11,12,4.231,7.461,9.180,6.186,8.266,7.103,6.392,10.484,5.267,...,6.102,7.765,7.260,6.391,5.395,6.853,8.733,8.722,4.966,10.679
12,13,5.618,8.477,6.935,13.042,17.595,8.331,7.436,16.494,6.412,...,7.473,11.032,8.626,8.835,5.067,10.780,6.868,7.930,10.681,18.849
13,14,4.689,5.453,8.715,9.196,7.949,15.573,6.182,6.075,6.520,...,5.726,5.548,10.211,8.091,4.071,3.477,3.643,7.271,13.604,6.007
14,15,7.260,10.731,7.742,7.239,7.920,12.412,4.751,10.636,9.578,...,10.065,3.761,8.780,10.105,8.758,5.561,6.588,8.909,9.290,10.039
15,16,4.231,15.876,7.745,7.193,5.019,8.432,6.794,8.004,6.704,...,5.882,10.152,9.021,11.481,8.273,4.073,28.261,12.314,6.959,7.478
16,17,6.466,6.601,7.794,11.584,8.156,10.204,5.201,7.427,5.962,...,8.232,7.724,6.727,7.778,9.669,14.033,7.218,6.641,7.066,6.908
17,18,6.187,4.944,8.117,8.999,17.903,16.397,5.445,5.792,6.705,...,6.570,9.006,6.900,8.276,4.373,7.221,5.596,13.471,6.732,5.300
18,19,4.689,11.994,16.322,8.647,13.832,6.164,5.253,8.414,7.448,...,7.294,9.182,9.919,15.627,6.288,5.852,6.815,6.966,10.368,8.374
19,20,5.649,6.027,8.313,7.321,9.078,9.931,5.024,11.840,8.679,...,5.893,4.745,6.938,6.936,5.739,6.147,5.790,6.774,48.935,14.712
20,22,5.510,6.697,8.451,8.677,12.498,6.513,6.350,6.689,7.670,...,8.469,10.666,7.215,12.328,3.512,9.078,11.210,6.311,7.486,7.974
21,23,5.988,8.397,8.327,10.521,8.457,7.216,3.831,6.437,6.720,...,6.676,10.906,6.369,7.463,5.443,5.580,7.755,6.395,7.299,7.133
22,24,9.020,9.766,8.232,9.223,7.536,7.049,2.643,5.206,7.469,...,6.658,7.218,7.380,6.418,5.088,5.683,5.323,6.698,5.356,6.644

In [27]:
df_result = pd.read_csv(rf'{original}rates_subject_mapping_layers.csv', sep= ";")

display(df_result)

df_pivot = df_result.pivot_table(
    index='Proband',
    columns=['MappingMethod', 'NumLayers'],
    values='Completed_Rel'
)

df_pivot.columns = [f"{l}_{t}" for l, t in df_pivot.columns]

df_result_spss = df_pivot.reset_index()

display(df_result_spss)

df_result_spss.to_csv(rf'{export}outcome_removed-inactive-{numSamplesForRemoval}_rmANOVA.csv', sep=";")

,Unnamed: 0,Proband,MappingMethod,NumLayers,Completed_Abs,Completed_Rel,Failed_Abs,Failed_Rel,Terminated_Abs,Terminated_Rel,Sum,Sum_Rel
0,0,1,densening,6,9,0.600000,0,0.000000,6,0.400000,15,1.0
1,1,1,densening,9,11,0.733333,0,0.000000,4,0.266667,15,1.0
2,2,1,densening,12,10,0.666667,0,0.000000,5,0.333333,15,1.0
3,3,1,densening,15,14,0.933333,0,0.000000,1,0.066667,15,1.0
4,4,1,densening,18,10,0.666667,0,0.000000,5,0.333333,15,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
409,409,24,widening,9,8,0.533333,2,0.133333,5,0.333333,15,1.0
410,410,24,widening,12,10,0.666667,1,0.066667,4,0.266667,15,1.0
411,411,24,widening,15,8,0.533333,0,0.000000,7,0.466667,15,1.0
412,412,24,widening,18,7,0.466667,4,0.266667,4,0.266667,15,1.0
413,413,24,widening,21,8,0.533333,3,0.200000,4,0.266667,15,1.0

,Proband,densening_6,densening_9,densening_12,densening_15,densening_18,densening_21,direct_6,direct_9,direct_12,direct_15,direct_18,direct_21,widening_6,widening_9,widening_12,widening_15,widening_18,widening_21
0,1,0.600000,0.733333,0.666667,0.933333,0.666667,0.666667,0.666667,0.800000,0.666667,0.600000,0.666667,0.666667,0.533333,0.533333,0.600000,0.666667,0.733333,0.466667
1,2,0.933333,1.000000,1.000000,0.866667,0.866667,0.866667,0.866667,0.866667,0.933333,0.933333,0.800000,0.666667,0.800000,0.866667,0.733333,0.466667,0.733333,0.666667
2,3,0.666667,0.733333,0.466667,0.800000,0.666667,0.400000,0.333333,0.333333,0.333333,0.400000,0.466667,0.400000,0.466667,0.533333,0.666667,0.600000,0.533333,0.600000
3,4,0.533333,0.733333,0.600000,0.466667,0.200000,0.400000,0.533333,0.533333,0.333333,0.333333,0.400000,0.333333,0.533333,0.533333,0.266667,0.200000,0.200000,0.266667
4,5,0.800000,0.866667,1.000000,0.666667,0.933333,0.800000,0.800000,0.800000,0.866667,0.666667,0.666667,0.600000,0.866667,0.600000,0.733333,0.666667,0.666667,0.600000
5,6,0.866667,0.933333,0.866667,1.000000,0.533333,0.600000,0.866667,0.666667,0.800000,0.666667,0.466667,0.800000,0.933333,0.666667,0.600000,0.733333,0.666667,0.533333
6,7,1.000000,0.933333,1.000000,0.600000,0.866667,0.466667,0.666667,0.866667,0.733333,0.800000,0.666667,0.733333,0.666667,0.600000,0.800000,0.666667,0.800000,0.600000
7,8,0.800000,0.733333,0.666667,0.733333,0.800000,0.533333,0.600000,0.866667,0.866667,0.866667,0.600000,0.733333,0.733333,0.533333,0.600000,0.666667,0.266667,0.666667
8,9,0.933333,0.800000,0.933333,0.866667,0.800000,0.866667,0.933333,0.933333,1.000000,0.933333,0.933333,0.866667,0.800000,0.600000,0.733333,0.666667,0.533333,0.466667
9,10,0.333333,0.333333,0.200000,0.666667,0.466667,0.466667,0.333333,0.466667,0.200000,0.133333,0.400000,0.333333,0.200000,0.266667,0.266667,0.266667,0.333333,0.333333
10,11,0.200000,0.266667,0.400000,0.533333,0.533333,0.333333,0.333333,0.600000,0.666667,0.733333,0.866667,0.600000,0.333333,0.333333,0.400000,0.333333,0.666667,0.400000
11,12,0.800000,0.933333,0.933333,0.866667,1.000000,0.866667,0.933333,1.000000,0.800000,0.800000,0.800000,1.000000,0.933333,0.733333,0.733333,0.600000,0.800000,0.600000
12,13,0.733333,0.866667,0.666667,0.666667,0.666667,0.933333,0.733333,1.000000,0.866667,0.800000,0.733333,0.533333,0.666667,0.800000,0.666667,0.666667,0.533333,0.733333
13,14,0.933333,0.666667,0.866667,0.733333,0.800000,0.933333,0.733333,1.000000,1.000000,0.866667,0.800000,0.933333,0.866667,0.800000,0.600000,0.666667,0.600000,0.666667
14,15,0.466667,0.933333,0.866667,0.866667,0.933333,0.933333,0.600000,0.800000,1.000000,0.933333,1.000000,1.000000,0.800000,0.866667,0.733333,0.800000,0.800000,0.733333
15,16,0.800000,0.600000,0.400000,0.533333,0.666667,0.666667,0.733333,0.600000,0.400000,0.533333,0.466667,0.400000,0.533333,0.333333,0.466667,0.333333,0.266667,0.133333
16,17,0.933333,0.866667,0.666667,0.800000,0.866667,0.600000,0.866667,0.933333,0.733333,0.866667,0.666667,0.666667,0.666667,0.666667,0.533333,0.333333,0.466667,0.600000
17,18,0.733333,0.933333,0.933333,0.866667,0.866667,0.666667,1.000000,1.000000,0.800000,1.000000,0.733333,0.933333,0.466667,0.933333,0.533333,0.800000,0.733333,0.800000
18,19,0.666667,1.000000,0.866667,0.866667,1.000000,0.800000,0.666667,0.800000,0.733333,0.800000,0.866667,0.866667,0.800000,0.666667,0.800000,0.733333,0.800000,0.600000
19,20,0.866667,0.933333,0.800000,0.666667,1.000000,0.533333,1.000000,1.000000,1.000000,0.666667,0.933333,0.933333,0.800000,0.800000,0.733333,0.733333,0.533333,0.666667
20,22,0.866667,0.866667,0.933333,0.933333,0.800000,0.933333,0.933333,0.933333,0.866667,0.866667,0.733333,0.733333,0.466667,0.666667,0.733333,0.600000,0.733333,0.666667
21,23,0.733333,0.866667,0.933333,0.866667,0.933333,0.800000,0.866667,0.933333,0.933333,1.000000,0.800000,0.933333,0.933333,0.933333,0.666667,0.800000,0.666667,0.733333
22,24,0.733333,0.800000,0.733333,0.600000,0.666667,0.866667,0.800000,0.733333,0.600000,0.666667,0.666667,0.600000,0.733333,0.533333,0.666667,0.533333,0.466667,0.533333

In [ ]:
df_terminated = pd.read_csv(rf'{original}Duration_terminatedTrials.csv', sep= ";")

display(df_terminated)

df_grouped = df_terminated.groupby(['Proband', 'Num_Layers'])['Duration'].mean().reset_index()

df_pivot = df_grouped.pivot(index='Proband', columns=['Num_Layers'], values='Duration')

# df_pivot.columns = [f"{m}_{l}" for m, l in df_pivot.columns]

df_terminated_spss = df_pivot.reset_index()

display(df_terminated_spss)

df_terminated_spss.to_csv(rf'{export}terminated-trials_rmANOVA-mean.csv', sep=";")

,Unnamed: 0,Proband,Block,Task,Trial,Date_Hold,Date_Start,Date_Terminated,Duration,Num_Layers,MappingMethod,Target_Layer
0,837,23,1,1,3,2021-06-29T07:20:04.369Z,2021-06-29T07:19:56.961Z,2021-06-29T07:20:04.496Z,0.127,12,direct,6
1,5632,23,1,6,0,2021-06-29T07:23:52.248Z,2021-06-29T07:23:48.441Z,2021-06-29T07:23:52.272Z,0.024,6,direct,5
2,7974,23,1,8,3,2021-06-29T07:25:50.663Z,2021-06-29T07:25:46.823Z,2021-06-29T07:25:51.221Z,0.558,9,direct,2
3,11188,23,1,11,3,2021-06-29T07:28:21.538Z,2021-06-29T07:28:15.519Z,2021-06-29T07:28:22.189Z,0.651,18,direct,17
4,13221,23,1,14,0,2021-06-29T07:30:06.352Z,2021-06-29T07:30:03.489Z,2021-06-29T07:30:06.477Z,0.125,6,direct,2
...,...,...,...,...,...,...,...,...,...,...,...,...
1721,1532988,12,3,16,3,2021-05-31T10:17:03.589Z,2021-05-31T10:16:58.377Z,2021-05-31T10:17:03.730Z,0.141,12,widening,1
1722,1533483,12,3,17,0,2021-05-31T10:17:27.710Z,2021-05-31T10:17:19.135Z,2021-05-31T10:17:28.673Z,0.963,9,widening,1
1723,1533643,12,3,17,1,2021-05-31T10:17:35.007Z,2021-05-31T10:17:30.127Z,2021-05-31T10:17:36.028Z,1.021,9,widening,2
1724,1534832,12,3,18,2,2021-05-31T10:18:30.573Z,2021-05-31T10:18:23.773Z,2021-05-31T10:18:31.158Z,0.585,15,widening,14
1725,1534998,12,3,18,3,2021-05-31T10:18:38.348Z,2021-05-31T10:18:32.948Z,2021-05-31T10:18:38.840Z,0.492,15,widening,4

Num_Layers,Proband,6,9,12,15,18,21
0,1,0.265111,0.397929,0.227400,0.246300,0.285692,0.337733
1,2,0.438833,0.463000,0.627333,0.360600,0.546000,0.518444
2,3,0.539762,0.438737,0.377913,0.376250,0.257632,0.354261
3,4,0.335810,0.459500,0.511778,0.519033,0.446697,0.608500
4,5,0.440625,0.189091,0.623500,0.560429,1.014364,0.773933
5,6,0.385600,0.401091,0.737818,0.652571,0.580368,0.515000
6,7,0.181100,0.554444,0.626429,0.639923,0.632222,0.670800
7,8,0.236538,0.411583,0.294077,0.370909,0.410000,0.396375
8,9,0.488400,0.129400,0.375800,0.483714,0.473364,0.387667
9,10,0.412692,0.351542,0.447862,0.357385,0.398667,0.335913
10,11,0.628906,0.458741,0.385913,0.463381,0.515643,0.525167
11,12,0.156800,0.572200,0.356500,0.555364,0.411333,0.540125
12,13,0.337846,0.090600,0.584750,0.658750,0.407312,0.278600
13,14,0.337143,0.666750,0.703875,0.557545,0.656750,0.545714
14,15,0.180941,0.439800,0.596000,0.444000,1.122333,0.604500
15,16,0.203167,0.526318,0.504920,0.422826,0.362739,0.444808
16,17,0.280143,0.350400,0.604917,0.715545,0.628077,0.447222
17,18,0.318167,0.981000,0.399909,0.261000,0.352625,0.306333
18,19,0.336583,0.416000,0.289556,0.387111,0.452800,0.419800
19,20,0.209800,0.645500,0.446571,0.536786,0.635750,0.281154
20,22,0.532091,0.518625,0.569429,0.547444,0.428909,0.775900
21,23,0.175000,0.577250,0.559000,0.927200,0.475333,0.404125
22,24,0.404500,0.690100,0.744615,0.655000,0.598727,0.788900

In [ ]:
df_peaks = pd.read_csv(rf'{original}all_peaks_stats.csv', sep= ";")

display(df_peaks)

df_pivot = df_peaks.pivot_table(
    index='Proband',
    columns=['MappingMethod', 'NumLayers'],
    values='Peaks_BeforeHold'
)

df_pivot.columns = [f"{l}_{t}" for l, t in df_pivot.columns]

df_peaks_spss = df_pivot.reset_index()

display(df_peaks_spss)

df_peaks_spss.to_csv(rf'{export}turning-points_rmANOVA.csv', sep=";")

,Unnamed: 0,Proband,Block,Task,Trial,NumLayers,MappingMethod,TargetLayer,Result,Peaks_Total,Peaks_BeforeHold,Peaks_AfterHold,Peaks_lower,Peaks_deeper,Peaks_between
0,0,1,2,6,3,6,densening,1,TERMINATED,2,2,0,1,0,1
1,1,1,2,9,3,6,densening,1,COMPLETED,2,2,0,1,1,0
2,2,1,2,16,4,6,densening,1,TERMINATED,3,3,0,1,1,1
3,3,2,3,4,4,6,densening,1,TERMINATED,1,1,0,1,0,0
4,4,2,3,7,4,6,densening,1,COMPLETED,2,2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6205,6205,23,2,6,0,21,widening,20,COMPLETED,0,0,0,0,0,0
6206,6206,23,2,14,2,21,widening,20,COMPLETED,3,3,0,3,0,0
6207,6207,24,3,2,1,21,widening,20,COMPLETED,3,3,0,3,0,0
6208,6208,24,3,9,3,21,widening,20,TERMINATED,1,1,0,1,0,0
6209,6209,24,3,17,4,21,widening,20,FAILED,1,1,0,1,0,0

,Proband,densening_6,densening_9,densening_12,densening_15,densening_18,densening_21,direct_6,direct_9,direct_12,direct_15,direct_18,direct_21,widening_6,widening_9,widening_12,widening_15,widening_18,widening_21
0,1,1.466667,1.533333,1.800000,1.933333,1.933333,1.933333,1.333333,2.866667,2.066667,1.733333,1.733333,1.866667,2.533333,1.066667,1.733333,1.800000,2.000000,1.866667
1,2,1.666667,3.000000,2.266667,3.533333,3.800000,4.266667,1.333333,2.400000,2.400000,2.333333,2.666667,3.266667,2.266667,3.533333,3.133333,2.600000,3.266667,3.533333
2,3,1.266667,2.666667,2.400000,5.533333,7.733333,7.466667,1.666667,2.400000,1.333333,2.400000,5.800000,4.400000,1.866667,2.400000,3.933333,5.733333,4.600000,5.400000
3,4,1.266667,2.133333,2.200000,5.600000,8.533333,5.600000,2.133333,2.000000,3.066667,5.066667,9.866667,8.866667,2.733333,3.866667,3.733333,6.266667,4.466667,7.800000
4,5,2.533333,2.600000,3.666667,2.333333,4.200000,3.266667,1.400000,2.133333,3.000000,3.066667,3.333333,3.733333,2.200000,1.800000,3.000000,2.866667,3.533333,3.266667
5,6,1.533333,1.600000,1.800000,2.133333,2.133333,2.066667,1.400000,1.600000,1.733333,2.400000,2.400000,2.200000,1.666667,2.866667,1.933333,2.200000,2.466667,2.733333
6,7,1.866667,2.266667,2.266667,3.133333,3.266667,4.466667,1.066667,1.466667,2.400000,2.466667,2.600000,3.000000,1.066667,1.466667,1.466667,2.133333,1.733333,2.400000
7,8,2.866667,3.266667,2.933333,3.933333,3.266667,5.066667,2.066667,2.066667,1.866667,4.333333,3.133333,3.933333,2.066667,2.000000,3.200000,2.266667,3.866667,3.600000
8,9,2.400000,3.533333,2.533333,4.866667,5.000000,4.200000,1.533333,2.200000,3.133333,5.000000,3.733333,3.133333,1.266667,1.866667,2.333333,3.800000,4.533333,5.266667
9,10,2.933333,2.200000,3.866667,4.866667,5.266667,6.733333,1.866667,2.733333,2.000000,3.600000,5.133333,6.466667,2.533333,1.666667,3.466667,3.200000,5.666667,3.333333
10,11,2.466667,1.533333,3.200000,2.000000,2.533333,3.266667,2.200000,1.933333,2.533333,3.800000,2.066667,3.600000,1.533333,0.933333,1.866667,2.266667,1.466667,1.733333
11,12,1.533333,2.133333,3.866667,3.133333,3.733333,3.533333,2.200000,3.466667,3.000000,4.333333,3.533333,4.533333,1.333333,2.533333,2.533333,3.000000,3.733333,4.133333
12,13,2.666667,2.333333,4.266667,2.866667,5.866667,5.000000,3.200000,2.933333,3.600000,4.800000,4.200000,3.066667,1.666667,2.733333,2.333333,4.333333,5.133333,4.066667
13,14,1.266667,2.133333,2.200000,3.000000,3.200000,3.266667,0.866667,1.800000,2.600000,2.133333,2.266667,2.133333,0.733333,3.466667,1.666667,3.400000,2.800000,4.200000
14,15,1.000000,1.666667,2.066667,2.400000,2.066667,3.600000,0.866667,1.466667,1.733333,2.333333,2.333333,2.333333,1.266667,1.200000,1.000000,2.133333,2.666667,1.666667
15,16,1.733333,2.666667,2.400000,4.000000,5.666667,5.000000,3.533333,3.333333,8.600000,6.266667,5.400000,10.133333,1.333333,2.733333,5.466667,9.000000,6.000000,12.666667
16,17,1.600000,2.000000,1.866667,3.266667,2.066667,2.533333,1.466667,1.733333,2.000000,2.333333,2.466667,2.200000,2.333333,2.533333,1.933333,3.400000,1.933333,2.533333
17,18,2.400000,1.733333,2.533333,2.600000,3.266667,3.000000,1.933333,2.000000,3.533333,2.333333,2.866667,2.266667,1.600000,2.533333,2.800000,2.400000,2.666667,3.266667
18,19,1.266667,1.466667,1.533333,1.933333,2.600000,1.533333,1.333333,1.733333,2.333333,3.066667,1.733333,2.133333,1.866667,1.533333,2.133333,2.000000,2.200000,2.133333
19,20,3.066667,2.266667,2.400000,3.533333,4.133333,3.133333,1.400000,2.000000,2.266667,2.866667,3.266667,3.666667,2.266667,2.133333,3.266667,2.066667,4.400000,3.066667
20,22,1.400000,1.800000,2.933333,2.666667,2.933333,2.666667,1.266667,1.866667,3.000000,2.933333,2.800000,2.066667,1.666667,1.200000,3.533333,2.733333,2.333333,3.600000
21,23,0.933333,2.066667,2.000000,2.400000,2.266667,3.266667,2.200000,2.533333,3.133333,3.733333,3.666667,3.066667,1.600000,2.066667,2.466667,2.466667,3.400000,4.533333
22,24,2.200000,3.266667,2.800000,2.866667,3.333333,5.400000,1.533333,1.733333,3.733333,2.600000,3.000000,3.266667,1.733333,1.400000,2.733333,2.333333,2.466667,3.800000